# change prifix
set-option -g prefix M-y

# start with 1 instead of 0
set -g base-index 1

# change default TERM
set -g default-terminal "screen"

# set mode-keys to vi instead of emacs
setw -g mode-keys vi

# no auto rename of windows
set -g allow-rename off

# move bar to top
set-option -g status-position top

# increase pane number display time
set -g display-panes-time 2000

# colors
set-option -g status-style  fg='#00cd00',bg='#2d2d2d'

# mac mouse fix
set-option -g mouse on
