"python stuff
set tabstop=4
set shiftwidth=4
set expandtab
set number
filetype indent on
set autoindent
let python_highlight_all = 1

syntax enable
set background=dark
let g:gruvbox_contrast_dark='hard'
let g:gruvbox_term_colors='16'
colorscheme gruvbox

"my preferences
set laststatus=2
set showmatch
set incsearch
map <F1> :set number!<CR>
map <F2> :set relativenumber!<CR>
map <F3> :set hls!<CR>
map <F4> :set nowrap!<CR> 
set viminfo= 
map <F5> :set pastetoggle<CR>
