"python stuff
set nocompatible
set t_Co=16
syntax enable
set background=light
colorscheme solarized
set cursorline
set colorcolumn=80
set tabstop=4
set shiftwidth=4
set expandtab
set number
let python_highlight_all = 1

"my preferences
set laststatus=2
set showmatch
set incsearch
map <F1> :set number!<CR>
map <F2> :set relativenumber!<CR>
map <F3> :set hls!<CR>
map <F4> :set nowrap!<CR> 
map <F5> :set pastetoggle<CR>
set lcs+=space:.
map <F6> :set list!<CR>
set viminfo= 
